[tool.bumpversion]
current_version = "2025.04.0"
parse           = "^(?P<year>\\d{4})\\.(?P<month>\\d{2})\\.(?P<patch>\\d+)$"
serialize       = ["{year}.{month}.{patch}"]
tag             = true
tag_name        = "v{new_version}"
commit          = true
message         = "Release: {new_version}"

[tool.bumpversion.parts.year]
type           = "calver"
calver_format  = "%Y"

[tool.bumpversion.parts.month]
type           = "calver"
calver_format  = "%m"

[tool.bumpversion.parts.patch]
type           = "integer"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search   = 'version = "2025.04.0"'
replace  = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/cpax/__init__.py"
ignore_missing_version = true
