name: cpax
channels:
  - conda-forge
dependencies:
  # core functionality
  - python=3.11
  - numpy>=1.24,<2.0
  - jax>=0.4.0
  - jaxlib>=0.4.0
  # Visualisation
  - matplotlib>=3.7
  # For testing
  - pytest
