[build-system]
requires = ["setuptools>=65.5", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CPax"
version = "2025.05.0"
description = "CPax: A JAX-based computational physics library."
requires-python = ">=3.12"
authors = [
  { name = "Jan Lukas Späh"}
]
license = { text = "MIT" }
readme = "README.md"
keywords = ["physics", "computational", "jax", "autograd", "ODE", "PDE"]
classifiers = [
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: MIT License"
]

dependencies = [
  "jax>=0.11",
  "numpy>=2.0",
  "matplotlib>=3.7",
]

[project.optional-dependencies]
dev = [
  "flake8",
  "pytest",
  "bump-my-version",
]
test = [
  "pytest",
]
docs = [
  "sphinx>=5.0",
  "sphinx-rtd-theme",
  "sphinx-autodoc-typehints",
  "sphinx-autoapi",
  "myst-parser"
]

[project.urls]
"Source" = "https://github.com/JaLuka98/CPax"
"Tracker" = "https://github.com/JaLuka98/CPax/issues"
