name: lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # Optionally, install your package in editable mode
        #pip install -e .
        
    - name: Run flake8
      run: |
        # Run flake8 on the src and tests directories
        flake8 src tests
