name: Manual CalVer Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry-run only? (no commit, no push)'
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bump-my-version
        run: pip install bump-my-version

      - name: Compute & (dry-)apply CalVer bump
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          set -e
          # Grab GH input (will be empty under act unless you simulate)
          INPUT_DRY_RUN="${{ github.event.inputs.dry_run }}"
          # If the runner already set DRY_RUN (via act --env), keep it;
          # otherwise fall back to the dispatch input.
          DRY_RUN="${DRY_RUN:-$INPUT_DRY_RUN}"

          # Now DRY_RUN comes from either --env DRY_RUN or from inputs.dry_run
          echo "DRY_RUN is: '$DRY_RUN'"
          
          # 1) Get latest tag or empty
          LATEST=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          YEAR=$(date +%Y)                # calendar year
          MONTH=$(date +%m)               # zero-padded month
          PREFIX="v${YEAR}.${MONTH}"

          if [[ "$LATEST" == $PREFIX.* ]]; then
            SEQ=${LATEST##*.}
            NEXT_SEQ=$((SEQ + 1))
          else
            NEXT_SEQ=0
          fi

          NEW_VERSION="${YEAR}.${MONTH}.${NEXT_SEQ}"
          echo "Next version will be ${NEW_VERSION}"

          # Build the bump command
          CMD="bump-my-version bump --new-version ${NEW_VERSION}"
          if [[ "$DRY_RUN" == 'true' ]]; then
            CMD+=" --dry-run --verbose --no-commit --no-tag"
          fi
          echo "Running: $CMD"
          $CMD

      - name: Push changes
        if: ${{ github.event.inputs.dry_run == false }}
        run: git push origin HEAD --follow-tags
